name: CI Workflow

on:
  push:
    branches:
      - main  # Déclenche le workflow sur un push dans la branche main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0' 

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Compiler l’application
      - name: Build application
        run: npm run build

      # Étape 5 : Exécuter les tests unitaires
      - name: Run tests
        run: npm test
